import './globals.css'
import React from "react";
// import ReactDOM from "react-dom/client";
import { StyledEngineProvider } from "@mui/material";
import 'tailwindcss/tailwind.css';

import Background from '@/components/layout/Background';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
  
    // <React.StrictMode>
		<StyledEngineProvider injectFirst>
      <Background>
			{children}
      </Background>
		</StyledEngineProvider>
	// </React.StrictMode>
  )
}
